SELECT * FROM EMP
SELECT * FROM DEPT
/*Aggregate function returns a single value, calculated values in a column */

SELECT MIN(SALARY) FROM EMP

SELECT SUM(SALARY) FROM EMP

SELECT SUM(SALARY) FROM EMP WHERE GENDER = 'MALE'

SELECT MAX(SALARY) FROM EMP WHERE GENDER = 'FEMALE'

SELECT COUNT(*) FROM EMP

SELECT COUNT(DEPTID) FROM DEPT

SELECT COUNT(SALARY) FROM EMP

SELECT AVG(SALARY) FROM EMP
