SELECT * FROM EMP
SELECT * FROM DEPT

CREATE VIEW vwEMPDEPT1
AS
SELECT ID, NAME, GENDER,DEPTNAME
FROM EMP
JOIN DEPT
ON EMP.DEPTID = DEPT.DEPTID

SELECT * FROM vwEMPDEPT1

DELETE FROM vwEMPDEPT1 WHERE ID = 1 /* View or function 'vwEMPDEPT1' is not updatable because 
the modification affects multiple base tables.
*/

CREATE TRIGGER tr_vwEMPDEPT1_InsteadOfDelete
ON vwEMPDEPT1
Instead Of Delete
AS
BEGIN
	DELETE EMP
	FROM EMP
	JOIN DELETED
	ON EMP.ID = DELETED.ID
END

SELECT * FROM vwEMPDEPT1

DELETE FROM vwEMPDEPT1 WHERE ID = 4

SELECT * FROM EMP
SELECT * FROM DEPT
