SELECT NAME,GENDER,SALARY, AVG(SALARY) OVER (ORDER BY SALARY) AS AVERAGE FROM EMP
/*Rows or Range clause is between Unbounded_preceeding(ist row) and current_row(2nd row) */

/*The OVER clause is used to determine which rows from the 
query are applied to the function, what order they are evaluated in by that function */

SELECT NAME,GENDER,SALARY, AVG(SALARY) OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
 AS AVERAGE FROM EMP /*here we got average of total , unbounded preceding means first row and unbounded following means last row*/

 SELECT NAME,GENDER,SALARY, AVG(SALARY) OVER (ORDER BY SALARY ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)
 AS AVERAGE FROM EMP /* here average done by one by one */

 SELECT GENDER,COUNT(*) AS TOTALGENDER,AVG(SALARY) AS AVERAGESALARY,MIN(SALARY) AS MINSALARY,MAX(SALARY) AS MAXSALARY FROM EMP GROUP BY GENDER

 SELECT NAME,SALARY,GENDER,COUNT(GENDER) OVER (PARTITION BY GENDER) AS NEWGENDER FROM EMP

 SELECT NAME,SALARY,GENDER, ROW_NUMBER() OVER(ORDER BY GENDER) AS ROWNUMBER FROM EMP
 /* the function ROW_NUMBER() must have clause OVER(ORDER BY) otherwise it will show error */

 SELECT NAME,SALARY,GENDER, ROW_NUMBER() OVER(PARTITION BY GENDER ORDER BY GENDER) AS ROWNUMBER FROM EMP
 /*by using partition by then gender will be separated into female and male and output also one by one */
 /*whenever partition changes Row_number is reset to 1 */

 SELECT NAME,GENDER,SALARY,LEAD(SALARY) OVER (ORDER BY SALARY) AS LEAD FROM EMP /*LEAD IS GOING TO LOOK UP NEXT ROW DATA */
 
 SELECT NAME,GENDER,SALARY,LAG(SALARY) OVER (ORDER BY SALARY) AS LAG FROM EMP /*LAG IS GOING TO LOOK UP AT PREVIOUS ROW DATA */
 SELECT * FROM EMP


 SELECT NAME,GENDER,SALARY,FIRST_VALUE(NAME) OVER (ORDER BY SALARY) AS FIRSTVALUE FROM EMP
 /* FOR THIS FIRST SALARY IS ARRANGED IN ASCENDING ORDER AND IN THAT WE RETRIEVE FIRST_NAME SO IT WILL RETURN IN FIRSTVALUE */

 SELECT NAME,GENDER,SALARY,FIRST_VALUE(NAME) OVER (PARTITION BY GENDER ORDER BY SALARY) AS FIRSTVALUE FROM EMP
 /* in this it will be divided into female and male */

 SELECT NAME,GENDER,SALARY, LAST_VALUE(NAME) OVER (ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LASTVALUE FROM EMP
 /*IN THIS WE GET HIGHEST PAID EMPLOYEE NAME AS LASTVALUE */
 /*last value function that it window starts at the first row and 
 window last at the last row in the result set*/


 SELECT NAME,GENDER,SALARY, LAST_VALUE(NAME) OVER (PARTITION BY GENDER ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LASTVALUE FROM EMP