CREATE TABLE PRODUCT1(productId int, name varchar(90),price int);

INSERT INTO PRODUCT1 VALUES(1,'MOBILE',25000);
INSERT INTO PRODUCT1 VALUES(2,'LAPTOP',45000);
INSERT INTO PRODUCT1 VALUES(3,'TELEVISION',35000);
INSERT INTO PRODUCT1 VALUES(4,'REFRIGERATOR',20000);
INSERT INTO PRODUCT1 VALUES(5,'WASHING MACHINE',30000);

CREATE TABLE SOLD(productId int,quantity_sold int);
INSERT INTO SOLD VALUES(1,34);
INSERT INTO SOLD VALUES(2,45);
INSERT INTO SOLD VALUES(4,78);
INSERT INTO SOLD VALUES(3,67);
INSERT INTO SOLD VALUES(5,23);
INSERT INTO SOLD VALUES(2,34);
INSERT INTO SOLD VALUES(1,45);
INSERT INTO SOLD VALUES(4,78);
INSERT INTO SOLD VALUES(1,67);
INSERT INTO SOLD VALUES(5,48);
INSERT INTO SOLD VALUES(3,23);



SELECT * FROM SOLD;
SELECT * FROM PRODUCT1;

Create View VWTOTALSALESPRODUCT
with schemaBinding
as select name,
SUM(ISNULL((quantity_sold * price),0)) as TotalSales,
COUNT_BIG(*) as TotalTransactions
from dbo.PRODUCT1
JOIN dbo.SOLD
ON PRODUCT1.productId = SOLD.productId
GROUP BY name

select * from VWTOTALSALESPRODUCT;




