CREATE TABLE DEPARTMENT1(DEPT_ID INT,DEPT_NAME NVARCHAR(90));
INSERT INTO DEPARTMENT1 VALUES(1,'IT');
INSERT INTO DEPARTMENT1 VALUES(2,'PAYROLL');
INSERT INTO DEPARTMENT1 VALUES(3,'HR');
INSERT INTO DEPARTMENT1 VALUES(4,'ADMIN');

CREATE TABLE TBLEMPLOYEE(ID INT, NAME NVARCHAR(90),SALARY INT,GENDER NVARCHAR(90),DEPT_ID INT);
INSERT INTO TBLEMPLOYEE VALUES(1,'LAKSHMI',15000,'FEMALE',3);
INSERT INTO TBLEMPLOYEE VALUES(2,'LAVANYA',20000,'FEMALE',2);
INSERT INTO TBLEMPLOYEE VALUES(3,'RAMU',30000,'MALE',4);
INSERT INTO TBLEMPLOYEE VALUES(4,'JEEVAN',21000,'MALE',1);
INSERT INTO TBLEMPLOYEE VALUES(5,'HITESH',22000,'MALE',2);
INSERT INTO TBLEMPLOYEE VALUES(6,'NANDU',23000,'FEMALE',4);
SELECT * FROM DEPARTMENT1;
SELECT * FROM TBLEMPLOYEE;


Create View VWEMPLOYEEBYDEPARTMENT1
AS
SELECT ID,NAME,SALARY,GENDER,DEPT_NAME FROM TBLEMPLOYEE JOIN DEPARTMENT1 
ON TBLEMPLOYEE.DEPT_ID = DEPARTMENT1.DEPT_ID


SELECT * FROM VWEMPLOYEEBYDEPARTMENT1;


Create View VWITEMPLOYEE
AS
SELECT ID,NAME,SALARY,GENDER,DEPT_NAME FROM TBLEMPLOYEE JOIN DEPARTMENT1 
ON TBLEMPLOYEE.DEPT_ID = DEPARTMENT1.DEPT_ID
WHERE DEPARTMENT1.DEPT_NAME = 'IT';

CREATE VIEW SUMMARIZEDDATA			/*it will show the total number of employee by that corressponding dept_names */
AS
SELECT DEPT_NAME,COUNT(ID) AS totalEmplooyees FROM TBLEMPLOYEE JOIN DEPARTMENT1 
ON TBLEMPLOYEE.DEPT_ID = DEPARTMENT1.DEPT_ID
GROUP BY DEPT_NAME;

SELECT * FROM SUMMARIZEDDATA;

SELECT * FROM VWITEMPLOYEE;

CREATE VIEW ENPLOYEEDATAEXCEPTSALARY
AS
SELECT ID,NAME,GENDER,DEPT_ID FROM TBLEMPLOYEE;

SELECT * FROM ENPLOYEEDATAEXCEPTSALARY;

UPDATE VWEMPLOYEEBYDEPARTMENT1
SET NAME ='UNISHA' WHERE ID = 3;

UPDATE VWEMPLOYEEBYDEPARTMENT1
SET NAME ='UNISHA', GENDER = 'FEMALE' WHERE ID = 3;

SELECT * FROM VWEMPLOYEEBYDEPARTMENT1;

UPDATE VWEMPLOYEEBYDEPARTMENT1
SET NAME ='RAM MOHAN' WHERE ID = 4;

