SELECT * FROM TBLEMPLOYEE

SELECT SUM(SALARY) FROM TBLEMPLOYEE		/*here we get sum of salary */

select min(SALARY) from TBLEMPLOYEE
SELECT MAX(SALARY) FROM TBLEMPLOYEE
SELECT AVG(SALARY) FROM TBLEMPLOYEE
SELECT COUNT(SALARY) FROM TBLEMPLOYEE	/* it prints number of rows in table */

/*aggregate function is a function where the values of multiple rows are grouped together as input on certain 
criteria to form a single value of more significant meaning.*/

SELECT NAME, SUM(SALARY) AS TOTALSALARY FROM TBLEMPLOYEE GROUP BY NAME;

SELECT NAME,GENDER, SUM(SALARY) AS TOTALSALARY FROM TBLEMPLOYEE GROUP BY NAME,GENDER;

SELECT NAME,GENDER,SUM(SALARY) AS TOTALSALARY, COUNT(ID) AS [TOTALEMPLOYEES] FROM TBLEMPLOYEE 
GROUP BY NAME,GENDER;

SELECT NAME,GENDER,SUM(SALARY) AS TOTALSALARY, COUNT(ID) AS [TOTALEMPLOYEES] FROM TBLEMPLOYEE 
WHERE GENDER = 'MALE'
GROUP BY NAME,GENDER;		/* where clause comes before GROUP BY but both have same meaning */

SELECT NAME,GENDER,SUM(SALARY) AS TOTALSALARY, COUNT(ID) AS [TOTALEMPLOYEES] FROM TBLEMPLOYEE 
GROUP BY NAME,GENDER
HAVING GENDER = 'MALE'	/*having clause comes after GROUP BY */

SELECT * FROM TBLEMPLOYEE WHERE SUM(SALARY) > 15000; /*An aggregate may not appear in the WHERE clause */

SELECT NAME,GENDER,SUM(SALARY) AS TOTALSALARY, COUNT(ID) AS [TOTALEMPLOYEES] FROM TBLEMPLOYEE 
GROUP BY NAME,GENDER
HAVING SUM(SALARY) > 15000  /* WE CAN USE AGGREGATE FUNCTIONS FOR THE HAVING CLAUSE */