SELECT * FROM TBLEMPLOYEE;
SELECT * FROM TBLDEPARTMENT
CREATE TABLE TBLDEPARTMENT(ID int,DEPARTMENTNAME nvarchar(50),LOCATION nvarchar(50),DEPARTMENTHEAD nvarchar(50));

INSERT INTO TBLDEPARTMENT VALUES(1,'IT','LONDON','RICK');
INSERT INTO TBLDEPARTMENT VALUES(2,'PAYROLL','DELHI','RON');
INSERT INTO TBLDEPARTMENT VALUES(3,'HR','NEWYORK','CHRISTOPHER');
INSERT INTO TBLDEPARTMENT VALUES(4,'OTHERDEPARTMENT','SYDNEY','CINDERILLA');


SELECT NAME,SALARY,GENDER,DEPARTMENTNAME FROM TBLEMPLOYEE
INNER JOIN TBLDEPARTMENT	
ON TBLEMPLOYEE.DEPT_ID = TBLDEPARTMENT.ID	/* by using inner join we can get matching rows only */

INSERT INTO TBLEMPLOYEE VALUES(7,'HEMANTH',34000,'MALE',NULL);
INSERT INTO TBLEMPLOYEE VALUES(8,'SIDDU',21000,'MALE',NULL);

SELECT NAME,SALARY,GENDER,DEPARTMENTNAME FROM TBLEMPLOYEE
LEFT OUTER JOIN TBLDEPARTMENT
ON TBLEMPLOYEE.DEPT_ID = TBLDEPARTMENT.ID	/* by using left join we can get matching and non matching rows */

SELECT NAME,SALARY,GENDER,DEPARTMENTNAME FROM TBLEMPLOYEE
RIGHT OUTER JOIN TBLDEPARTMENT
ON TBLEMPLOYEE.DEPT_ID = TBLDEPARTMENT.ID /*by using right join we can get here in TBLPERSON  other department
										 not assigned ,but that records also we will get in output. */

SELECT NAME,SALARY,GENDER,DEPARTMENTNAME FROM TBLEMPLOYEE
FULL OUTER JOIN TBLDEPARTMENT
ON TBLEMPLOYEE.DEPT_ID = TBLDEPARTMENT.ID /* by using full outer join we will get left and right join records */

SELECT NAME,SALARY,GENDER,DEPARTMENTNAME FROM TBLEMPLOYEE
CROSS JOIN TBLDEPARTMENT	/*by using cross join, the number of rows in employee table is 
							being multiplied by the number of rows in department table */