


CREATE TABLE WEDNESDAY1(ID INTEGER PRIMARY KEY, FIRST_NAME NVARCHAR(90),LAST_NAME NVARCHAR(90),AGE INT);

INSERT INTO WEDNESDAY1 VALUES(1,'LAKSHMI','AVULA',21);
INSERT INTO WEDNESDAY1 VALUES(2,'LAVANYA','B.KR',25);
INSERT INTO WEDNESDAY1 VALUES(3,'NANDINI','AVULA',19);
INSERT INTO WEDNESDAY1 VALUES(4,'NAGARAJU','AVULA',42);
INSERT INTO WEDNESDAY1 VALUES(5,'SAVITHRI','AVULA',38);
INSERT INTO WEDNESDAY1 VALUES(6,'DEEKSHA','B.K',8);
INSERT INTO WEDNESDAY1 VALUES(7,'RAMU','B.KR',30);
INSERT INTO WEDNESDAY1 VALUES(8,'HETHAN','B.KR',7);
INSERT INTO WEDNESDAY1 VALUES(9,'HITI','B.KR',7);

SELECT * FROM WEDNESDAY1 WHERE LAST_NAME = 'AVULA' ORDER BY AGE; 
SELECT * FROM WEDNESDAY1 WHERE ID>5 ORDER BY AGE;
SELECT * FROM WEDNESDAY1 WHERE AGE > 9 ORDER BY FIRST_NAME;